name: Publish Release
on:
  workflow_dispatch:
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 25

      - name: Setup Gradle Caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup Gradle Wrapper
        run: chmod +x gradlew

      - name: Get Properties
        id: properties
        run: |
          echo "version=$(grep -m1 "^version=" gradle.properties | cut -c 9-)" >> $GITHUB_OUTPUT
          echo "mcVersion=$(grep -m1 "^minecraft = " gradle/libs.versions.toml | cut -c 14- | rev | cut -c 2- | rev)" >> $GITHUB_OUTPUT

      - name: Publish Release
        run: ./gradlew publish
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASSWORD }}

      - name: Upload NeoForge Releases (Curse/Modrinth/Github)
        id: neoforge_release
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: ${{ vars.CURSE_ID }}
          curseforge-token: ${{ secrets.CURSE_TOKEN }}

          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: ./neoforge/build/libs/!(*-@(dev|sources|dev-shadow)).jar
          name: "[NeoForge] CTM Reborn ${{ steps.properties.outputs.version }}"
          version: ${{ steps.properties.outputs.version }}
          version-type: release
          changelog-file: changelog.md
          loaders: neoforge
          game-versions: ${{ steps.properties.outputs.mcVersion }}
          version-resolver: exact

      - name: Upload Fabric Releases (Curse/Modrinth/Github)
        id: fabric_release
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: ${{ vars.CURSE_ID }}
          curseforge-token: ${{ secrets.CURSE_TOKEN }}

          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: ./fabric/build/libs/!(*-@(dev|sources|dev-shadow)).jar
          name: "[Fabric] CTM Reborn ${{ steps.properties.outputs.version }}"
          version: ${{ steps.properties.outputs.version }}
          version-type: release
          changelog-file: changelog.md
          loaders: fabric
          game-versions: ${{ steps.properties.outputs.mcVersion }}
          version-resolver: exact
